### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by CodeGuy92** [meow-js/meow-js#2]
i used the code in the example, and...
```
/home/runner/PROJECT NAME/node_modules/meowing/src/lib/request.js:21
    headers.Cookie = opts.client?.auth?.cookie;
                                 ^

SyntaxError: Unexpected token '.'
```

**Comment by FunctionalMetatable** [comment]
Are you using replit?

**Comment by CodeGuy92** [comment]
> Are you using replit? If so, it looks like you're not on the latest version of node. I think you should update to node.js v14 if you can

ok
